[WIP] Vyper implementation of DAppStore
andytudhope/theStateOfUs pull request #9
Opened 2019-03-12 13:50 UTC by vyomshm

@andytudhope 

written a first implementation for DAppStore.

2019-03-13 11:09 UTC, jacqueswww requested changes
This looks pretty good, I made some inline comments.
- Some docblock/natspec comments per function would be nice
- Add `.vy linguist-language=Python` to the `.gitattributes` in root so we can get vyper files syntax in color :)

@andytudhope 

- It's difficult to know if everything is working, is there same tests or minimum parts we can test against? Currently it's difficult to know if anything is missing, I checked mostly at the what the code does and compared a bit to solidity.

2019-03-13 11:09 UTC, jacqueswww commented on vyper/DAppStore.vy
> +    return extract32(_data, 4, type=bytes32)
I would remove these and and just stick to using the function inline, not only does it improve readability of what is actually happening it will be an awesome gas saving (trust me really big) ;)

2019-03-13 11:09 UTC, jacqueswww commented on vyper/DAppStore.vy
> +    return extract32(_data, 4, type=bytes32)
Just add `#  decode id` comment if you feel it's unclear. For all 3 the decode functions.

2019-03-13 11:09 UTC, jacqueswww commented on vyper/DAppStore.vy
> +SNT: ERC20
Vyper has a built-in ERC20 interface, see if this would suffice? 
```python
from vyper.interfaces import ERC20
...
SNT: ERC20
```

2019-03-13 11:09 UTC, jacqueswww commented on vyper/DAppStore.vy
> +    assert self.SNT.transferFrom(_from, self, _amount)
Vyper also supports asserts with reason string, so I would recommend to add them like the solidity contract.

```python
assert a != 2, "a is not 2"
```

2019-03-13 11:09 UTC, jacqueswww commented on vyper/DAppStore.vy
> +    #TO-DO:??
@andytudhope So this made me wonder:
I think for this implementation we can just leave it as a TODO? Or just comment it out? 
To be honest we have to be careful with updating the ceiling - as isn't it a potential single point of failure that could make the whole contract void (even with a DAO/Governance behind it, those can be hacked too).

Additionally the curve could be unfairly tuned for members early or late into staking game ? Unless we make the stakers actually vote?

2019-03-13 11:09 UTC, jacqueswww commented on vyper/DAppStore.vy
> +    e_balance: uint256
@andytudhope @vyomshm having full variable names is always more readable for future contract readers:
```python
votes_minted
votes_cast
effective_balance
```
Would suggest changing it on solidity contract as well.

2019-03-13 11:53 UTC, vyomshm commented on vyper/DAppStore.vy
> +SNT: ERC20
I saw that too.

But the specs called for a `MiniMe` token implementation and vyper currently has only ERC20 and ERC721 as built-in choices.

2019-03-13 11:53 UTC, vyomshm commented
I forgot to add a TO-DO list.

High Level Changes : 
- [ ] Add Comments
- [ ] testing utility
- [ ] update `.gitattributes ` to get python syntax highlighting

Code Improvements :
- [ ] add reason strings to assert statements
- [ ] full variable names to improve readability
- [ ] move all decode`id, sig, amount` functionality inline into `receiveApproval`
- [ ] update `ERC20` contract to include methods from `MiniMe` token contract

Questions : 

1. `MiniMe` token interface implements `approveAndCall` with one of it's params as `bytes _extraData` but vyper doesn't allow for variable length bytes arrays.
 Based on [giveth's implementation](https://github.com/Giveth/minime/blob/ea04d950eea153a04c51fa510b068b9dded390cb/contracts/MiniMeToken.sol#L258), can I assume `_extraData` is always passed into `receiveApproval` and therefore can be restricted to `bytes[132]` ?

@jacqueswww @andytudhope .

2019-03-13 11:56 UTC, jacqueswww commented
I think that is a safe assumption for now, it can always be increased later if needed.

2019-03-13 13:44 UTC, andytudhope commented on vyper/DAppStore.vy
> +    #TO-DO:??
Yeah, I agree that we leave it out entirely for now 👍And just back ourselves hard to come up with sensible reasons for choosing the ceiling we do that can at least be partially justified. If worst comes to worst and SNT shoots up/down, we can always re-deploy and migrate with a new ceiling.

2019-03-13 13:48 UTC, jacqueswww commented on vyper/DAppStore.vy
> +    #TO-DO:??
Perfect :)

2019-03-13 13:49 UTC, andytudhope commented
Yeah, I agree with @jacqueswww that that is safe assumption for now. Thanks for the TODO list too, that helps.

I think `v_minted` is clear enough tbh, but don't have strong feelings on it. What do you think @vyomshm? Perhaps it is better to follow the advice of an actual engineer and go with `votes_minted` 😜

As for tests, that is next on my list of things to think about. Tbh, I only have experience writing JS tests, because testing in Solidity is even worse than trying to do maths safely... Either way, I think it should be a separate bounty that @vyomshm can tackle after the above TODO list. As there will also be at least one other bounty to implement George and Limechain's awesome SQRT library: https://github.com/andytudhope/Recollections/issues/4#issuecomment-472098452

2019-03-13 14:48 UTC, vyomshm commented
@andytudhope  @jacqueswww 

I changed the variables name for(v_minted, v_cast and e_balance) on both the DAppStore  implementations. It never hurt anyone to be explicit.

2019-03-14 10:59 UTC, andytudhope commented on vyper/DAppStore.vy
> +    #TO-DO:??
Please remove this entirely for now @vyoshm

2019-03-14 11:03 UTC, andytudhope commented
@vyomshm please remove entirely the `updateCeiling` function for now, and squash your commits and I will then merge so that we can create additional bounties for 1) Proper tests and 2) Implementing the exponent (which, as a fraction, is a square root) properly. @jacqueswww has kindly offered to do a PR with a barebones pytest framework 😉

2019-03-14 11:35 UTC, vyomshm commented
@andytudhope Done!

2019-03-15 06:07 UTC, merged